メッセージ投稿：スクロール制御
solufa/violet pull request #28
Opened 2021-09-27 15:42 UTC by maihrs55

- 新規メッセージ投稿時にスクロールが最下部に動く機能
    - 別work読み込み後、Revisionが存在するworkに移動した場合にも
        メッセージが表示されるように修正
    - 投稿したメッセージが即時表示されるように修正

![image](https://user-images.githubusercontent.com/52160187/134940366-fa556e7a-d216-4458-a64a-2121da663042.png)

↓

![image](https://user-images.githubusercontent.com/52160187/134940493-74ee6c38-a01b-426b-872a-9d9caaf7e9a3.png)

2021-09-29 16:08 UTC, solufa commented on pages/browser/[...pathes]/usePage.ts
> +        revisions: revisions,
めっちゃ些細だけど、 `revisions,` 一回で書ける

2021-09-29 16:08 UTC, solufa requested changes
ちょっとだけ修正お願いします

2021-09-29 23:49 UTC, maihrs55 commented on pages/browser/[...pathes]/usePage.ts
> +        revisions: revisions,
修正をしたのですが、ご指摘に応えられているかご確認をお願いします。
revisions の値をmessages の値へ使っていました。

2021-10-03 04:40 UTC, maihrs55 commented
issue/10-2に対応内容が含まれているのでクローズします。

2021-10-03 04:40 UTC, closed without merging