リプライカードUI
solufa/violet pull request #31
Opened 2021-10-06 14:14 UTC by maihrs55

リプライカードUIを作成しました。
レビューを宜しくお願いいたします。（リプライはインデントを入れるなどした方が見やすいでしょうか）

以下、未実装です。テストデータで動作を見ています。
APIからリプライリストをリビジョン分取得して、画面表示する処理

### 画面イメージ

![image](https://user-images.githubusercontent.com/52160187/136218895-54281103-842d-4913-8b24-042d8e0001d8.png)

2021-10-07 02:43 UTC, solufa commented on pages/browser/[...pathes]/components/StreamBar/ReplyMessageCell.tsx
> +        <>
mapの下はKeyが必要
`<> === <React.Fragment>`
なので
`<React.Fragment key={hoge}>`

2021-10-07 02:44 UTC, solufa commented on pages/browser/[...pathes]/components/StreamBar/ReplyMessageCell.tsx
> +  margin-bottom: 12px;
Spacer使っているのにさらにM-bottom当てる意味がない
Spacerに統一

2021-10-07 02:45 UTC, solufa commented on pages/browser/[...pathes]/components/StreamBar/ReplyMessageCell.tsx
> +  font-size: 80%;
fontsizeはpx指定に統一するほうが使いやすい

2021-10-07 02:50 UTC, solufa commented on pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
> +  const repliesByMessageId = () => {
使ってないらしい

2021-10-07 02:50 UTC, solufa requested changes
ここまで修正お願いします

2021-10-09 11:04 UTC, maihrs55 commented on pages/browser/[...pathes]/components/StreamBar/ReplyMessageCell.tsx
> +  overflow: hidden;
overflowは特に効果がない要素でしたので、削除しました。

2021-10-10 14:03 UTC, solufa approved these changes
LGTM

2021-10-10 14:03 UTC, merged